### ISSUE TITLE
`googlemaps` fails while running for the first time

### ISSUE THREAD

**Issue by joelwallis** [googlemaps/google-maps-services-js#107]
I got an error when I ran `googlemaps` for the first time.

Here are the steps to reproduce:

- Install it globally (`npm i -g @google/maps`)
- Run it (`googlemaps`)

It was expected to return a friendly error message (generally it's the same output for the `--help` flag), but instead I got an error (`Error: apiCall is not a function`).

FYI: I tried to execute it as `googlemaps <my API key>` but I got the same error.

**Comment by stephenmcd** [comment]
I can't reproduce this using the latest version. It may have been an issue with an earlier version. Please re-open if you can reproduce it with the latest version.

**Comment by dzuluaga** [comment]
@joelwallis I ran into similar issue when I tried to run the command without an API key. Two things to consider:

**1. set GOOGLE_MAPS_API_KEY first** $ export GOOGLE_MAPS_API_KEY=<your API key>
**2. Do not use `googlemaps <my API key>`. Use `googlemaps <available operation>` command along with the operation as a second argument** e.g. `googlemaps directions ...`. This argument matches the function available from google client ([see run.js line 22](https://github.com/googlemaps/google-maps-services-js/blob/ef6dcc7e7669ed84cad3d5224a89bb261476f1b9/bin/run.js#L22)) will retrieve a function with this name. Available operations from Google Client: 
```
directions,
distanceMatrix,
elevation,
elevationAlongPath,
geocode,
geolocate,
reverseGeocode,
places,
placesNearby,
placesRadar,
place,
placesPhoto,
placesAutoComplete,
placesQueryAutoComplete,
snapToRoads,
nearestRoads,
speedLimits,
snappedSpeedLimits,
timezone
```

@stephenmcd if possible, I'd recommend checking for GOOGLE_MAPS_API_KEY env variable to see it's set. If it's not, it'd be great to provide a more meaningful error instead of `apiCall is not a function`. Also, maybe supporting  passing the API key as an argument is not a bad idea.

My 2 cents.
Hope it helps!

**Comment by joelwallis** [comment]
@stephenmcd, I just reproduced it using the most recent version:

```
~❯ env | grep GOOGLE
~❯ npm i -g @google/maps
/Users/joel/.nvm/versions/node/v8.5.0/bin/googlemaps -> /Users/joel/.nvm/versions/node/v8.5.0/lib/node_modules/@google/maps/bin/run.js
+ @google/maps@0.4.5
added 1 package in 3.17s
~❯ googlemaps
Error: apiCall is not a function
```

@dzuluaga thanks for the help! I'll try the env variable now.

**Comment by joelwallis** [comment]
Also, I'm unable to reopen this issue. There's no option in GitHub's UI.

**Comment by stephenmcd** [comment]
Sorry, I originally missed that you were using the CLI incorrectly.

I just pushed a change which gives a more useful error message: de079e72498ef268ba4b521c62d11bfa83e983f8
