### ISSUE TITLE
placesAutoComplete sessiontoken is required but maybe shouldn't be?

### ISSUE THREAD

**Issue by zjr** [googlemaps/google-maps-services-js#191]
https://github.com/googlemaps/google-maps-services-js/blob/master/lib/apis/places.js#L285

Should `sessiontoken` be a required parameter to `placesAutoComplete`?

These [docs](https://developers.google.com/places/web-service/autocomplete) say otherwise and the parameter wasn't required in previous versions of this lib.

Am I just missing something?

**Comment by stephenmcd** [comment]
It's new which is why it didn't exist in previous versions.

The docs for rest API state that it's optional, however the intention of this client library is to make things easier for you the developer. In this case, the library is ensure you don't get overcharged, by making the sessiontoken mandatory.
