### ISSUE TITLE
Error flow not working as expected

### ISSUE THREAD

**Issue by mr-bobz** [googlemaps/google-maps-services-js#32]
Thanks for providing a formal Node.js Client library for Google Maps Services 👍 

But, I ended up wasting many hours to find out why my geocoding API calls stopped working suddenly with no error :-(

Investigating into it, found that instead of an error, the response had this:

> { error_message: 'Browser API keys cannot have referer restrictions when used with this API.',
>   results: [],
>   status: 'REQUEST_DENIED' }

Given there is an error(err) object in the callback function, shouldn't that be set as well for proper error handling instead of sticking the error message just to the response object?

``` javascript
// Geocode an address.
googleMapsClient.geocode({
  address: '1600 Amphitheatre Parkway, Mountain View, CA'
}, function(err, response) {
  if (!err) {
    console.log(response.json.results);
  }
});
```

**Comment by stephenfarrar** [comment]
This is a very good point. At the moment the library is a very thin wrapper around the HTTP response. Lots of status 200 responses are actually errors.

The docs say that the error callback is only called with errors from the underlying http package:
https://googlemaps.github.io/google-maps-services-js/docs/ResponseCallback.html

So if we were to surface other errors in the error callback, we'd need to provide some way to distinguish between a network error and a server-generated error.

Thoughts?

**Comment by migueloller** [comment]
It would be fairly trivial to distinguish the 2.

- If the status isn't 200, call the callback just how it is now.
- If the status is 200 but `response.json.status` is not `"OK"`, call the callback with an error built from the`response.json.status` and `response.json.error_message`.
- If the status is 200 and `response.json.status` is `"OK"`, call the callback without an error.

Does this work?

**Comment by jharrowmortelliti** [comment]
Could the change be made in bin/run.js?  That is where the error handling is done now.

**Comment by stephenfarrar** [comment]
@migueloller I was thinking about how to write an error handler.
I guess it could go something like this:

```
googleMapsClient.geocode(...).asPromise()
    .catch(function(err) {
        if (err == 'timeout')  {
            // do something
        } else if (err.json) {
            // this would be HTTP status 200 but error status in the JSON response.
        } else {
            // this would be a network-level error.
        }
    });
```

Does that seem usable and obvious?

**Comment by migueloller** [comment]
@stephenfarrar,

If the HTTP status is 200 would the promise be rejected? It looks like the problem is that adding something like `catch` or checking for the error in the callback is not working because the request doesn't actually fail (i.e., status is 200) but results in an error on Google's end.

It looks like one would have to implement the logic I mentioned above [here](https://github.com/googlemaps/google-maps-services-js/blob/master/lib/internal/make-api-call.js#L107).

**Comment by stephenfarrar** [comment]
@migueloller 
Yes, I think we're talking past each other.

You are thinking about how the library should be implemented (and what you've said makes total sense).

I am thinking about how the library would be used, because I want to check that it's going to be more usable. Let's suppose that HTTP status 200 responses that are not "OK" turn into promise rejections. Then, what sort of code do you want to write?

**Comment by migueloller** [comment]
@stephenfarrar,

Ah I see. Sorry for the confusion. What you wrote above looks like the way to go!

For people still using callbacks then it would be the same, except that the rejected error would be the error (first) argument of the callback.

**Comment by migueloller** [comment]
Do you think it might be convenient to expose the request in the error object? Perhaps if a developer wants to catch the error and then log information pertaining to the request that failed (i.e., headers)?

Maybe something like this?
```js
googleMapsClient.geocode(...).asPromise()
    .catch(function(err) {
        if (err == 'timeout')  {
          console.error('The request timed out.');
        } else if (err.request.ok) {
          console.error('The request failed with error message: ' + err.request.error_message);
          console.error('The headers were: ' + err.request.headers );
        } else {
          console.error(err.message);
        }
    });
```

**Comment by stephenfarrar** [comment]
https://developers.google.com/places/web-service/search#PlaceSearchStatusCodes

For the Places API, the possible status codes are: `OK`, `ZERO_RESULTS`, `OVER_QUERY_LIMIT`, ...

@migueloller Do you think that `ZERO_RESULTS` should be an error?

Also, I've created a pull request #54. Let me know what you think.

**Comment by migueloller** [comment]
@stephenfarrar,

Because `ZERO_RESULTS` "indicates that the search was successful but returned no results." and also, "Even if the service returns no results (such as if the `location` is remote) it still returns an empty `results` array.", I think that it shouldn't be treated as an error.

I looked over #54 and it looks good overall. Perhaps if we don't treat `ZERO_RESULTS` as an error then that case would have to be added. Also, I left a comment with a question regarding the Response API.

Thanks for implementing this!

**Comment by migueloller** [comment]
@stephenfarrar,

By the way, I must stay that the way you've approached this, taking care to make sure that everything is up to the client's (developers that use this library, me in this case) standards is admirable. Many OSS developers just implement what first comes to mind but you've included others (me) along the way.

Thanks for that!
