### ISSUE TITLE
Sourcing only required module

### ISSUE THREAD

**Issue by pasupulaphani** [googlemaps/google-maps-services-js#35]
Hi all,

Please consider this as a suggestion.

One of our microservices uses only geocoder hence I was trying to see if I could only source the required script.

Something like:
```
const Geocode = import "@google/maps/geocode"
```

What do you think?

**Comment by stephenfarrar** [comment]
Just to make sure I've understood the motivation.
Do you want to reduce the size of the source code?
Or do you want to skip the step of creating a client object?

In fact, all of the API methods use the same JS, and are simply configured to hit a different URL. So splitting up the module into multiple modules isn't really feasible.

**Comment by pasupulaphani** [comment]
reduce the size of the source code

**Comment by stephenmcd** [comment]
Since this is a server-side library, the code size shouldn't be a concern. On top of that, if you inspect how the library is structured, you'll find that each of the APIs are implemented declaratively, so there's no actual extra code for each API, just some configuration data.

Given that, we won't address this, but thanks for the suggestion all the same.
