### ISSUE TITLE
place/queryautocomplete vs. place/autocomplete

### ISSUE THREAD

**Issue by sumpton** [googlemaps/google-maps-services-js#44]
Thank you for this module.

placesAutoComplete seems to work great, but when I was looking for query autocomplete

https://developers.google.com/places/web-service/query

and according to that page, the url to call is "/place/queryautocomplete/"

https://maps.googleapis.com/maps/api/place/queryautocomplete/output?parameters

which appears to be the same as here for "Places"

https://github.com/googlemaps/google-maps-services-js/blob/master/lib/apis/places.js#L191

On this page for place autocomplete

https://developers.google.com/places/web-service/autocomplete

the url called is "/place/autocomplete/"

https://maps.googleapis.com/maps/api/place/autocomplete/output?parameters

Are they mixed up? Are they interchangeable?

**Comment by stephenmcd** [comment]
Thanks for raising this, there's definitely an error there which we'll need to resolve. To be clear, the URLs definitely aren't interchangeable, and serve different purposes.

**Comment by tonybadguy** [comment]
While trying to figure out why the types filter wasn't working, I realized that it's related to this issue. Because the function is using /queryautocomplete which doesn't support the type filter, it's being ignored.

Any thoughts on what the fix will be? I've switched the endpoint to /autocomplete on my fork, but don't want to stray too far from your planned fix.
