### ISSUE TITLE
[question] What does `timeout` really mean?

### ISSUE THREAD

**Issue by wujekbogdan** [googlemaps/google-maps-services-js#69]
I have a script that makes a lot of google maps API calls (geocoding). Requests are made less than 50 times a second (50 is a Google Maps API limit). After a minute or so, google-maps-services-js starts to returning an error: `timeout`. 

I've dug into sources, and I found that this happens in the `make-api-calls.js` external module. Does timeout simply mean that a request was sent to the Google Maps API but no response was returned?

I have a poor internet connection. Is it possible that this is the reason and I should simply make less API calls per second and increase the timeout limit (passing a timeout parameter to the client)?

**Comment by stephenfarrar** [comment]
The default rate limit in the client library is 10 per second. It sounds like you'll want to up this to 50. You have to do this when creating the client object:

```
const client = createClient({
  key: 'your API key here',
  rate: {limit: 50},
});
```

Because of the client-side rate limit, your geocoding calls are queued. If they wait in the queue for longer than `timeout` they will be cancelled. Probably, no request was sent to Google. (It's also possible that requests timed out waiting for a response, but it seems less likely.)

If you're willing to let requests wait in the queue for longer, increase the timeout.

**Comment by wujekbogdan** [comment]
Oh, thanks. I didn't know that I can define the rate in options. I already use a [limiter module](https://www.npmjs.com/package/limiter), so maybe it would be good to use such kind of limiter in the `google-maps-services-js`?

PS
IMO the limit should be increased. Google allows for up to 50 requests per second, so why to limit it to 0 by default, it's a bit confusing.
